### ISSUE TITLE
[Bug] Broken in Safari Mobil and Desktop

### ISSUE THREAD

**Issue by itportal24** [creativetimofficial/ct-nextjs-material-kit-pro#1]
### Version
1.0.0
### Reproduction link
https://itportal24-git-template-vanilla.itportal.now.sh/
### Operating System
OSX, iOS
### Device
MacBook, iPhone
### Browser & Version
Latest updates on both devices
### Steps to reproduce
1. Install like the creative tim docs say.
2. Visit page in Safari.
Use iPhone or set User-Agent to iPhone, if the bug does not show directly on desktop Safari.
Sometimes it will only show after one or two page reloads.
### What is expected?
The presentation page without issues.
### What is actually happening?
There is a grey bar on top.
Most of the components are not displayed at all.
Most of the proportions are quirked.
The main-card is cut of like this for example.
![bildschirmfoto_2019-12-06_um_13 50 16](https://user-images.githubusercontent.com/58595737/70330983-e52a1200-183e-11ea-9ace-334730ccec2a.png)

---
### Additional comments
The code is untouched, I did not make any changes.
While in development mode everything is working fine, but local in production mode or remote deployment with Zeit/Now shows the bug.

**Comment by EINazare** [comment]
Hello there, @itportal24 ,

Thank you for your interest in working with our products.
I've searched for the bug, and I believe it comes from the Parallax component. For some reason, when NextJS bundles the styles, it adds the Parallax styles on the Main component as well.
At the moment I honestly do not know what the fix could be other than:
1. Go inside `assets/jss/nextjs-material-kit-pro/pages/presentationStyle.js`
2. Change the following code:
```
  main: {
    ...main
```
To
```
  main: {
    ...main
    overflow: initial !important;
    height: 100% important;
    background-position: unset !important;
```

Let me know if this solved your issue.

Best,
Manu

**Comment by itportal24** [comment]
Hi, thanks for the quick reply.

The components are now displayed, but the header image is now gone.
![2019-12-07-153908_1920x1080_scrot](https://user-images.githubusercontent.com/58595737/70376302-cf345400-1907-11ea-8489-e4cdb60289af.png)

This is the code I applied, because your suggested changes are not exactly valid jss.

`
  main: {
    ...main,
    overflow: "initial !important",
    height: "100% !important",
    backgroundPosition: "unset !important"
  }
`

**Comment by EINazare** [comment]
Hello again, @itportal24 ,

What do you mean that the mage is missing?
Did you delete it?

Best,
Manu

**Comment by itportal24** [comment]
I reinstalled from scratch out of the .zip Archive and applied your suggested fix again.
Image is now shown and the components are displayed.

BUT:
On Safari Mobile there is now a grey bar on the top of the site where you can see the background.
Please have a look at the deployment.

https://itportal24-git-template-vanilla.itportal.now.sh/

I could invite you to the gitlab repo if that helps.

**Comment by EINazare** [comment]
Hello again, @itportal24 ,

I've tested your link on an iPhone Safari and on a Mac Safari. 
It seems to me that the image appears on both devices.
Can you please send me a screenshot?

Best,
Manu

**Comment by itportal24** [comment]
Hi,
What I meant was, that the picture is now showing but it is not aligned to the top.
There is a small stripe on top. This is only happening is Safari.
I would suspect its from the parallax, something which is not canceld out by your fix?

![Bild von iOS](https://user-images.githubusercontent.com/58595737/70634722-0752d400-1c33-11ea-8992-83df7d40506d.png)
![Bildschirmfoto 2019-12-11 um 11 16 15](https://user-images.githubusercontent.com/58595737/70634732-0ae65b00-1c33-11ea-908a-522ba2126c31.png)

**Comment by EINazare** [comment]
Hello again, @itportal24 ,

Really sorry about this, didn't notice it before.
Please go inside `assets/jss/nextjs-material-kit-pro/components/parallaxStyle.js` and at line 24 add the following code:
```
,
    marginTop: "0!important"
```

Let me know if you have further issues.

Best,
Manu

**Comment by itportal24** [comment]
You are not fusing Material-UI and NextJS together the right way.
Have a look at [https://github.com/mui-org/material-ui/tree/master/examples/nextjs](url).
Most importantly you are not removing the Serversheets:

```JavaScript
// _app.js
componentDidMount() {
    // Remove the server-side injected CSS.
    const jssStyles = document.querySelector('#jss-server-side');
    if (jssStyles) {
      jssStyles.parentElement.removeChild(jssStyles);
    }
  }
```
This is why there css-classes which have the same name, but different styles.
Where Firefox/Chrome mostly just use the latest class they see, Safari will default back to User-Agent-Style.

After I changed everything to match the example 100% everything is working now.

**Comment by mlasy** [comment]
Hey @itportal24 i'm experiencing the same issue, been trying for a week now but couldnt get it fixed.
I tried the SSR as described here https://material-ui.com/de/guides/server-rendering/
But it didnt work. 
Could you provide a link with how you exactly solved it?
