### ISSUE TITLE
[Feature Request] Convert _app and _index into modern functional components

### ISSUE THREAD

**Issue by smarteventandproduction** [creativetimofficial/ct-nextjs-material-kit-pro#10]
### What is your enhancement?
We are trying to refactor a React app into a Nextjs app and we thought it would be a lot easier to code and refactor if the _index and _app components were already in a modern, functional format - instead of being older class components. This is just an easy and minor change, but it will be a huge improvement. I hope that you will seriously consider this. Thanks!

**Comment by EINazare** [comment]
Hello there, @smarteventandproduction ,

Thank you for your interest in working with our products.
We've checked the official docs of NextJS, and there is no way of changing the class components from `_app` and `_document` to functional ones. Here is a link: https://nextjs.org/docs/advanced-features/custom-document

If you have any idea on how that could be achieved, please share with me your code at manu@creative-tim.com.

Best,
Manu
