### ISSUE TITLE
[Bug] Incompatible with next-images > 1.3.1

### ISSUE THREAD

**Issue by jwlawrence** [creativetimofficial/ct-nextjs-material-kit-pro#11]
### Version
1.1.0
### Reproduction link
https://www.creative-tim.com/new-issue/nextjs-material-kit-pro
### Operating System
OSX
### Device
Mac Book Pro
### Browser & Version
Chrome 89.0.4389.90
### Steps to reproduce
1. Bump next-images to 1.4.0 or higher
2. Build nextjs-material-kit-pro app
3. Get the following error:

error - ./assets/scss/nextjs-material-kit-pro.scss?v=1.1.0
ModuleParseError: Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
### What is expected?
Successful build
### What is actually happening?
Build fails with:

error - ./assets/scss/nextjs-material-kit-pro.scss?v=1.1.0
ModuleParseError: Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

---
### Additional comments
I don't know how to provide a basic reproduction without standing up the entire project.
Seeing as how the next-images README advertises this theme I think this should be a priority.

**Comment by EINazare** [comment]
Hello there, @jwlawrence ,

Please revert the next-images back to `v1.3.1`. 
In the last year, we've tried multiple ways of integrating the new versions, but with no success.

Best,
Manu
