### ISSUE TITLE
[Bug] conflict issue using v1.2

### ISSUE THREAD

**Issue by jhyoo2** [creativetimofficial/ct-nextjs-material-kit-pro#16]
### Version
1.2
### Reproduction link
https://www.creative-tim.com/
### Operating System
npm 
### Device
mac
### Browser & Version
chrome
### Steps to reproduce
just install it with npm install
### What is expected?
When using v1.2 there is some conflict between react-animate-on-scroll and react library.

I attach the detail about it.

npm ERR! While resolving: nextjs-material-kit-pro@1.2.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR! react@"17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@">= 15.4.1 < 17.0.0-0" from react-animate-on-scroll@2.1.5
npm ERR! node_modules/react-animate-on-scroll
npm ERR! react-animate-on-scroll@"2.1.5" from the root project

### What is actually happening?

I solve this problem by install with force option, but I have some worry about it.

Is it okay to install with force option?

---

**Comment by EINazare** [comment]
Hello there, @jhyoo2 ,

I think the issue comes from NodeJS and npm. Please download and install NodeJS LTS version, and also npm version 6.

Best,
Manu

**Comment by cerebralkungfu** [comment]
Still an issue;  NodeJS LTS v14.7.3 and NPM 7.21.0.

**Comment by NLAvL** [comment]
@cerebralkungfu i had the same problem and ones solved i found the comment of einazare. Since debugging for one hour can save you 2 minutes of reading the docs... well, i figured you mind want to know by know ;)   

please try npm version 14.8.2 along with npm v 6.14.15

```
nvm use 14
Now using node v14.18.2 (npm v6.14.15)
```
