### ISSUE TITLE
[Bug] Customizable Select with MultiSelect jumps after selecting

### ISSUE THREAD

**Issue by VsevolodEpinetov** [creativetimofficial/ct-nextjs-material-kit-pro#17]
### Version
1.2.0
### Reproduction link
https://demos.creative-tim.com/nextjs-material-kit-pro/components
### Operating System
Windows 10
### Device
Chrome
### Browser & Version
90.0.4430.212 64bit
### Steps to reproduce
1. Open dropdown of multiselect input
2. Click on any option
3. Repeat 2 on other option if it didn't work
### What is expected?
The option is selected, dropdown menu is staying in place
### What is actually happening?
The option is indeed selected, but menu jumps for whatever reason. If menu has greater amount of inputs, the 'jump' might be pretty huge.

---

**Comment by sajadevo** [comment]
Hi there,

It's not an issue it's the default behavior of the component coming from material-ui.

Regards,
Sajad
