### ISSUE TITLE
Responsive header does not perform correctly when dropdown used

### ISSUE THREAD

**Issue by tomgreeEn** [creativetimofficial/ct-nextjs-material-kit-pro#2]
STEPS TO REPRODUCE

This issue is evident on the live demo site:
https://demos.creative-tim.com/nextjs-material-kit-pro/presentation
...and also if you do a new clean install locally.

1. Open the main page on desktop (tested with Safari, Chrome)
2. Reduce the width of the browser, to, say 900 px - so not full width, but before the header links are collapsed into the mobile menu
3.  open one of the dropdown menus on the header, e.g. COMPONENTS

ISSUE

When the menu opens, the tooltip box pushes down the entire header, so that everything becomes out of line.

EXPECTED BEHAVIOUR

 The dropdown should appear over the main body of the page, so that the header does not change size. 
This is the behaviour in the bootstrap version of the demo site:

https://demos.creative-tim.com/material-kit-pro/presentation.html

**Comment by EINazare** [comment]
Hello there, @tomgreeEn ,

I do not follow your issue, please check the attached images:
![Screen Shot 2020-01-31 at 10 07 41 AM](https://user-images.githubusercontent.com/26245512/73522643-97322480-4411-11ea-9b1e-809ab708330a.png)
![Screen Shot 2020-01-31 at 10 07 47 AM](https://user-images.githubusercontent.com/26245512/73522644-97322480-4411-11ea-9a9d-5ebece9bc99c.png)

Best,
Manu

**Comment by tomgreeEn** [comment]
Hi Manu
Please see attached screenshots -
1) Chrome Version 79.0.3945.130 (Official Build) (64-bit)
2) Version 13.0.4 (15608.4.9.1.3)

I checked the breakpoint, it's actually at 1280px if that helps. 

Tom

![Screenshot 2020-01-31 at 11 24 07](https://user-images.githubusercontent.com/4262865/73535956-baae9c80-441c-11ea-9254-002c00b25691.png)

![Screenshot 2020-01-31 at 11 26 53](https://user-images.githubusercontent.com/4262865/73535975-c13d1400-441c-11ea-8c70-20a68703aacb.png)

**Comment by tomgreeEn** [comment]
Apologies, the 900px was misleading as this is actually after the menu collapses - it's between 960px - 1280px that there is an issue.

**Comment by tomgreeEn** [comment]
Hi @EINazare - any update on this? Were you able to reproduce it?
Thanks

**Comment by EINazare** [comment]
Hello again, @tomgreeEn ,

Really sorry about this late response, I've had a few days off due to some personal issues.
Go inside: `assets/jss/nextjs-material-kit-pro/components/customDropdownStyle.js`
And change `[theme.breakpoints.down("md")]: {` with `[theme.breakpoints.down("sm")]: {`.

That will do the trick.

Let me know if you have further issues.

Best,
Manu

**Comment by tomgreeEn** [comment]
Brilliant, thank you!
