### ISSUE TITLE
[Bug] nom install fails

### ISSUE THREAD

**Issue by valduk** [creativetimofficial/ct-nextjs-material-kit-pro#20]
### Version
1.2.0
### Reproduction link
https://github.com/creativetimofficial/ct-nextjs-material-kit-pro
### Operating System
OS X 11.5.2
### Device
MacBook Pro 
### Browser & Version
v16.2.0
### Steps to reproduce
1. Download kit (react link)
2. Do npm install (--force)
### What is expected?
Npm install completes successfully 
### What is actually happening?
lots of errors:
npm ERR! gyp ERR! node -v v16.2.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

---

**Comment by khiz-k** [comment]
I'm getting this too.  Paid so much for this and the product doesn't work? lol

**Comment by sajadevo** [comment]
**Hi @valduk **

Thanks for using our product we're working on the product update and it will be available on JAN 2022 for a quick fix you can use yarn like so:
1. Download and install yarn globally using npm: **npm i -g yarn**
2. Run the following command on the product root directory: **yarn install**

**All the best
Sajad**
