### ISSUE TITLE
[Bug] Cannot install the software using `npm install`

### ISSUE THREAD

**Issue by agxc** [creativetimofficial/ct-nextjs-material-kit-pro#24]
Registered an issue with `nextjs-material-kit-pro@1.2.0` but encountered the following errors.  
![Screen Shot 2022-04-18 at 4 58 39 pm](https://user-images.githubusercontent.com/10444895/163772334-24d9e772-893f-48b6-90c8-1cb99ffae6ea.png)

**Comment by sajadevo** [comment]
> Registered an issue with `nextjs-material-kit-pro@1.2.0` but encountered the following errors. ![Screen Shot 2022-04-18 at 4 58 39 pm](https://user-images.githubusercontent.com/10444895/163772334-24d9e772-893f-48b6-90c8-1cb99ffae6ea.png)

**Hi @agxc**

Thanks for using our product, please use `npm i --legacy-peer-deps` and it will fix the issue.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**

**Comment by agxc** [comment]
Hi @sajadevo 
Thanks for your very prompt response. I tried `npm i --legacy-peer-deps`. It didn't work for the first time, but I tried `npm i --force` and it worked. Also, the documentation suggests to  use `npm start` afterwards when  it supposes to use `npm run dev`.

**Comment by sajadevo** [comment]
@agxc 

We will fix that issue for the next update of the product. 🙏🏻
