### ISSUE TITLE
[Bug] multiple errors and warnings when running the app

### ISSUE THREAD

**Issue by JianWang2016** [creativetimofficial/ct-nextjs-material-kit-pro#28]
### Version
1.3.1
### Reproduction link
https://www.creative-tim.com/new-issue/nextjs-material-kit-pro
### Operating System
macOS monterey version 12.6
### Device
macbook pro
### Browser & Version
Chrome Version 108.0.5359.124 (Official Build) (x86_64is up to date)
### Steps to reproduce
>cd kit
>npm run dev
go to localhost:3000
visit different pages
turn on inspect console
### What is expected?
free of errors and a few warnings
### What is actually happening?
navigating the pages for 3 minutes, I see 19 errors and 62 user messages.

---
### Solution
The warnings are all related to react 18 no longer supporting ReactDom.render so it should be a quick fix in your next release.  The errors seem to be caused by including google map api multiple times causing issues and some other issues related type errors.  
### Additional comments
I also have a few other questions: 

1) I use next 13 in my own application and I see you are at next 12.  Do you anticipate problems when I integrate some of your components?
2) the absolute path reference link in the document does not describe what strategy you use.  I think it is a great thing to use absolute path. Could you please be specific about how you implemented the absolute path in your app?  Thanks so much for the beautiful design and app!
3) the file structure on the document is no longer accurate after you moved files to the public folder
4) do you have a roadmap for future releases? I am particularly interested in when the nextjs 13 will be online.

**Comment by JianWang2016** [comment]
Hi, I resolved the google api key issue. Need provide my own key at _app.js.

I see in your [demo](https://demos.creative-tim.com/nextjs-material-kit-pro/) you don't have the ReachDom.render not supported by react 18.  Am I using a different version of the pro kit? It would be great if I can also have the good version as your demo one.  Thanks so much.

**Comment by sajadevo** [comment]
@JianWang2016,

I've tested the product and it works smoothly could you please check your product version on the package.json the latest version is v1.3.1 and it works well with React 18

Cheers,
Sajad

**Comment by JianWang2016** [comment]
Thanks @sajadevo for your response.  I did use version 1.3.1

Got tons of this warning at the browser console. 
next-dev.js?3515:20 Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/lin

**Comment by sajadevo** [comment]
@JianWang2016 I think it's an issue with Next.js 13 because it's still in beta as the product is used React 18 and it's not React 17 but I'll try to find a workaround for that.

**Comment by sajadevo** [comment]
This issue is fixed on v.1.3.2
