### ISSUE TITLE
[Bug] the header component when clicking on an item (e.g. components, sections, examples) when opening the menu with the options (e.g. Presentation Page, All components, Documentation) this menu instead of appearing under the buttons it overlaps and hides the items (ex: components, sections, examples) , different from the behavior that appears on your site

### ISSUE THREAD

**Issue by Carlos-Filho-IOT** [creativetimofficial/ct-nextjs-material-kit-pro#29]
### Version
1.3.1
### Reproduction link
https://creative-tim.com/
### Operating System
Windows 10
### Device
Desktop
### Browser & Version
Microsoft Edge 109.0.1518.70
### Steps to reproduce
1 - Click an item on the Header menu
### What is expected?
The menu should appear under the button (item) that was clicked.
### What is actually happening?
appears in the middle of the button (item), hiding the same

---

**Comment by Carlos-Filho-IOT** [comment]
![image](https://github.com/creativetimofficial/ct-nextjs-material-kit-pro/assets/84594275/e43dead8-9afc-452d-b108-43721b188206)

**Comment by sajadevo** [comment]
This issue is fixed on v1.3.2
