### ISSUE TITLE
[Bug] Typo in documentation page Typo

### ISSUE THREAD

**Issue by hans2103** [creativetimofficial/ct-nextjs-material-kit-pro#3]
### Version
n.a.
### Reproduction link
https://demos.creative-tim.com/nextjs-material-kit-pro/documentation/styles
### Operating System
OS
### Device
MacBook Pro
### Browser & Version
Chrome 79.0.3945.130
### Steps to reproduce
1. Go to https://demos.creative-tim.com/nextjs-material-kit-pro/documentation/styles
2. Read the third line of the documentation. 
```
We've decided to use the makeStyles function from Material-UI to override some of thier styles.
```
### What is expected?
Expecting to read the word "their"
### What is actually happening?
Reading the word "thier"

---
### Solution
Fix the typo by replacing the word "thier" by the word "their"

**Comment by EINazare** [comment]
Hello there, @hans2103 ,

We'll check and solve this as soon as possible.

Best,
Manu
