### ISSUE TITLE
[Bug] Hover/ripple on ecommerce page partially obscured

### ISSUE THREAD

**Issue by tomgreeEn** [creativetimofficial/ct-nextjs-material-kit-pro#5]
### Version
1.0.0 (according to package.json)
### Reproduction link
 https://www.creative-tim.com/new-issue/nextjs-material-kit-pro
### Operating System
mac os
### Device
MacBook pro
### Browser & Version
chrome  80.0.3987.149 (Official Build) (64-bit)
### Steps to reproduce
Go to the ecommerce demo page (link above)
* Hover over the filter choices in the sidebar on the left
- > The hover only partially shows, it's clipped along the left hand side

* Click on an item
- > the ripple is similarly obscured, clipped along the left hand side
### What is expected?
Should see the full circle of hover/ripple
### What is actually happening?
It's obscured by the block to the left

---
### Solution
Presumably I need to change the relative zIndexes - but initial tests haven't worked

**Comment by EINazare** [comment]
Hello there, @tomgreeEn ,

The link you have given sends me to open a new issue for the product at hand, please provide me with the link of the page your are having issues.
Also, you could provide me with a small video of the issue happening.

Best,
Manu

**Comment by tomgreeEn** [comment]
Hi
Apologies - the correct link is here:

https://demos.creative-tim.com/nextjs-material-kit-pro/ecommerce

You shouldn't need a video if you follow the steps provided. 

This is also an issue on Safari, where in fact the formating is even more broken.

Tom

**Comment by EINazare** [comment]
Hello there, @tomgreeEn ,

I've checked with my colleagues, the only solution is to add `disableRipple` on the Checkboxes from the e-commerce page, that is what we've done on the HTML counterpart of this product: https://demos.creative-tim.com/material-kit-pro/examples/ecommerce.html
So you have to change the checkboxes from: 
```
<Checkbox
                                  tabIndex={-1}
                                  onClick={() => handleToggle(9)}
                                  checked={
                                    checked.indexOf(9) !== -1 ? true : false
                                  }
                                  checkedIcon={
                                    <Check className={classes.checkedIcon} />
                                  }
                                  icon={
                                    <Check className={classes.uncheckedIcon} />
                                  }
                                  classes={{
                                    checked: classes.checked,
                                    root: classes.checkRoot
                                  }}
                                />
```
To
```
<Checkbox
                                  tabIndex={-1}
                                  onClick={() => handleToggle(9)}
                                  disableRipple
                                  checked={
                                    checked.indexOf(9) !== -1 ? true : false
                                  }
                                  checkedIcon={
                                    <Check className={classes.checkedIcon} />
                                  }
                                  icon={
                                    <Check className={classes.uncheckedIcon} />
                                  }
                                  classes={{
                                    checked: classes.checked,
                                    root: classes.checkRoot
                                  }}
                                />
```
Also, I found another bug, the hover background, that should not happen, for this, go inside `assets/jss/nextjs-material-kit-pro/customCheckboxRadioSwitchStyle.js` and change:
```
  checkRoot: {
    padding: "14px",
    "&:hover": {
      backgroundColor: "unset"
    }
  },
  radioRoot: {
    padding: "16px",
    "&:hover": {
      backgroundColor: "unset"
    }
  },
```
To
```
  checkRoot: {
    padding: "14px",
    "&:hover": {
      backgroundColor: "unset !important"
    }
  },
  radioRoot: {
    padding: "16px",
    "&:hover": {
      backgroundColor: "unset !important"
    }
  },
```

Best,
Manu

**Comment by tomgreeEn** [comment]
Hi

Thanks, but this isn’t really a fix, it’s just switching the feature off !

I assume I’ll need to add some padding to the block and then give it some negative margin to position it back in the same space.

What was the change to the stylesheet supposed to achieve? As far as I can tell it’s not done anything for me and I still get the hover, partially cropped.

Tom

**Comment by EINazare** [comment]
Hello again, @tomgreeEn ,

I've checked with my colleagues, the only solution is to add `disableRipple` on the `Checkboxes` from the e-commerce page, that is what we've done on the HTML counterpart of this product: https://demos.creative-tim.com/material-kit-pro/examples/ecommerce.html 
Please check the above link.
That area is far too small to add some more padding to it, the inside UI will be distorted on smaller screens.

We have forgotten to disable the ripple effect on the Checkboxes, that ripple effect should not happen anyway. There is no way to fix this, the only fix is to disable the ripple, at least on the e-commerce page.

Best,
Manu
