### ISSUE TITLE
[Bug] Cannot get basic setup to work

### ISSUE THREAD

**Issue by BTProjects** [creativetimofficial/ct-nextjs-material-kit-pro#7]
### Version
1.0.0
### Reproduction link
https://jsfiddle.net/#&togetherjs=HMQxCQ5Izo
### Operating System
Apple
### Device
Mac Book Pro
### Browser & Version
Chrome 80.0.3987.162 
### Steps to reproduce
I've installed the product as directed in the documentation.  I'm using the default NextJS "hello-nextjs" application.
I've created a project level next.config.js file and included all items from the next.config.js within the project folder next-js-material-kit-pro-v1.0.0.  
I've installed all necessary components from next.config.js
It appears the next.config.js copied is set to utilize absolute paths as described in the documentation

### What is expected?
I should be able to include components in the index file and produce them.
### What is actually happening?
I'm getting an error: Module not found: Error: Can't resolve 'assets/jss/nextjs-material-kit-pro/components/badgeStyle.js' in '/Users/linaar/repos/hello-next/nextjs-material-kit-pro-v1.0.0/components/Badge'

All of the folders and assets are present as expected.  It appears that the index is picking up the actual component reference but then I get this error.

---
### Additional comments
I can provide the whole project if necessary.  It's just the most basic nextjs startup application.

**Comment by EINazare** [comment]
Hello there, @BTProjects ,

Thank you for your interest in working with our products.
Please revert the changes back to what our project comes with - we'll make an update to this product (to use the latest NextJS API) in the following days.

Best,
Manu

**Comment by BTProjects** [comment]
Thank you.  I did find that if I unzip your product to an empty project folder and run npm start from there it does build out a workable solution.  I was having issues integrating into a new project.  I think part of my problem as well was that I assumed I would have a root component folder specific to nextjs-material-pro-version components or something of that nature but ultimately the components go under the root component folder.  All styles, refs, etc use absolute paths to that root folder.
