### ISSUE TITLE
Select passing native property to control component

### ISSUE THREAD

**Issue by israellopeztiscareno** [creativetimofficial/ct-nextjs-material-kit-pro#8]
Passing the native property to the Select component, there are no styles for this property since it is not based on the hidden input, the event needs to be handled.

![Captura de Pantalla 2020-04-22 a la(s) 13 12 09](https://user-images.githubusercontent.com/63254555/80018000-0496a400-849b-11ea-9946-6ba8c53d1d42.png)

**Comment by EINazare** [comment]
Hello there, @israellopeztiscareno ,

Thank you for your interest in working with our products.
Please check our live docs here: 

- https://demos.creative-tim.com/nextjs-material-kit-pro/documentation/tutorial
- https://demos.creative-tim.com/nextjs-material-kit-pro/documentation/file-input
- https://demos.creative-tim.com/nextjs-material-kit-pro/documentation/select

Best,
Manu
